# Numpy Interview Questions

# 1. What exactly is Numpy?

NumPy, which stands for Numerical Python, is a fundamental package for scientific computing in Python. It provides support for arrays (including multidimensional arrays), along with a large collection of high-level mathematical functions to operate on these arrays.

Key features of NumPy include:

- **ndarray**: An efficient multidimensional array providing fast array-oriented arithmetic operations and flexible broadcasting capabilities.

- **Mathematical functions**: A large set of mathematical functions for fast operations on entire arrays of data without having to write loops.

- **Linear algebra, random number generation, and Fourier transform capabilities**.

- **Tools for integrating code written in C, C++, and Fortran**.

Because arrays in NumPy are more efficient than Python lists for certain operations, NumPy can be used to perform mathematical calculations on large amounts of data with better performance.

Here's a simple example of using NumPy:



In [1]:
import numpy as np

# Create a NumPy array
a = np.array([1, 2, 3])

# Perform a mathematical operation on the array
b = a + 2

print(b)  # Outputs: array([3, 4, 5])

[3 4 5]




In this example, we first import the NumPy module. Then, we create a NumPy array `a` with the values 1, 2, 3. Finally, we add 2 to each element of the array using a single operation, demonstrating NumPy's ability to perform vectorized operations.

# 2. What is the purpose of NumPy in Python?

NumPy, short for Numerical Python, serves several purposes in Python:

1. **Efficient Numeric Operations**: NumPy provides the `ndarray` object for efficient storage and manipulation of dense data buffers in Python. The arrays are more efficient and performant than Python's built-in list data structure.

2. **Mathematical Operations**: NumPy provides a comprehensive set of mathematical functions to perform operations on these arrays. These include arithmetic operations, statistical operations, linear algebra operations, and more.

3. **Interoperability**: NumPy arrays can be used to interface with C/C++ and Fortran code, which is useful for integrating legacy code or utilizing high-performance libraries.

4. **Broadcasting**: NumPy provides functionality to perform operations between arrays of different shapes, which is known as broadcasting. This makes it easier to perform matrix computations.

5. **Base for Other Libraries**: NumPy serves as the foundational package for scientific computing in Python. Many other libraries in the scientific Python ecosystem, such as pandas, matplotlib, and scikit-learn, are built on top of NumPy and rely on its array and mathematical functionality.




# 3. What does Python's NumPy stand for?

NumPy (pronounced /nmpa/ (NUM-py) or /nmpi/ (NUM-pee)) is a Python
library that adds support for huge, multi-dimensional arrays and matrices,
as well as a vast number of high-level mathematical functions to work on
these arrays.


# 4. Where does NumPy come into play?
NumPy is a free, open-source Python library for numerical computations. A
multi-dimensional array and matrix data structures are included in NumPy,
and it may execute many operations on arrays, including trigonometric,
statistical, and algebraic algorithms. NumPy is a Numeric and Numarray
extension.

# 5. Installation of Numpy into Windows?

To install NumPy on Windows, you'll need to have Python and pip, the Python package installer, already installed on your system. If you have these, you can install NumPy by opening a command prompt (cmd) and typing the following command:



In [ ]:
pip install numpy



If you have both Python 2 and Python 3 installed on your system, and you want to install NumPy for Python 3, you might need to use `pip3` instead:



In [ ]:
pip3 install numpy



If you're using a Python virtual environment, make sure to activate the environment before running the install command.

If you encounter permission issues, try using the `--user` flag:



In [ ]:
pip install --user numpy



Remember to replace `pip` with `pip3` if you're using Python 3.

If you don't have Python or pip installed, I recommend installing the Anaconda distribution of Python, which comes with NumPy, pandas, and many other useful libraries for scientific computing and data analysis. You can download Anaconda from the official website: https://www.anaconda.com/products/distribution.

# 6. What is the best way to import NumPy into Python?

Import NumPy as np

# 7. How can I make a one-dimensional(1D)array?

You can create a one-dimensional (1D) array in NumPy using the `numpy.array()` function and passing in a list as an argument. Here's an example:



In [2]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]




In this example, we first import the NumPy module. Then, we create a 1D NumPy array `arr` with the values 1, 2, 3, 4, 5. Finally, we print the array.

The `numpy.array()` function is a central data structure of the NumPy library. You can create an array from numerical ranges with `numpy.arange()` function, or filled with constant or random values using `numpy.zeros()`, `numpy.ones()`, or `numpy.random.random()`, respectively.

# 8. How can I make a two-dimensional (2D)array?

You can create a two-dimensional (2D) array in NumPy using the `numpy.array()` function and passing in a list of lists as an argument. Each sublist will be a row in the 2D array. Here's an example:



In [3]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]




In this example, we first import the NumPy module. Then, we create a 2D NumPy array `arr` with the values 1, 2, 3 in the first row, 4, 5, 6 in the second row, and 7, 8, 9 in the third row. Finally, we print the array.

The `numpy.array()` function is a central data structure of the NumPy library. You can also create a 2D array filled with constant or random values using `numpy.zeros()`, `numpy.ones()`, or `numpy.random.random()`, respectively.

# 9. How do I make a 3D or ND array?

You can create a three-dimensional (3D) or N-dimensional array in NumPy using the `numpy.array()` function and passing in a nested list as an argument. Each sublist represents a higher dimension in the array. Here's an example of creating a 3D array:



In [4]:
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]




In this example, we first import the NumPy module. Then, we create a 3D NumPy array `arr`. The outermost list contains two elements, each of which is a 2D array. Finally, we print the array.

The `numpy.array()` function is a central data structure of the NumPy library. You can also create a 3D or ND array filled with constant or random values using `numpy.zeros()`, `numpy.ones()`, or `numpy.random.random()`, respectively.

# 10. What is the best way to use a shape in a 1D array?

The shape of an array in NumPy is a tuple that indicates the size of each dimension. For a 1D array, the shape will be a tuple with just one element, which is the length of the array.

You can get the shape of an array using the `shape` attribute, and you can reshape an array without changing its data using the `reshape` method. Here's an example:



In [5]:
import numpy as np

# Create a 1D array
arr = np.array([1, 2, 3, 4, 5, 6])

# Print the shape of the array
print("Shape:", arr.shape)

# Reshape the array to a 2D array with 2 rows and 3 columns
arr_reshaped = arr.reshape((2, 3))

print("Reshaped array:")
print(arr_reshaped)

Shape: (6,)
Reshaped array:
[[1 2 3]
 [4 5 6]]




In this example, we first create a 1D NumPy array `arr` with the values 1, 2, 3, 4, 5, 6. Then, we print the shape of the array, which is `(6,)`. After that, we reshape the array to a 2D array with 2 rows and 3 columns, and print the reshaped array.

Note that the total size of the array must remain the same after the reshape. In this case, the original array has 6 elements, and the reshaped array has 2*3=6 elements.

# 11. What is the best way to use shape in a 2D array?

The shape of a 2D array in NumPy is a tuple that indicates the number of rows and columns. You can get the shape of an array using the `shape` attribute, and you can reshape an array without changing its data using the `reshape` method.

Here's an example:



In [6]:
import numpy as np

# Create a 2D array
arr = np.array([[1, 2, 3], [4, 5, 6]])

# Print the shape of the array
print("Shape:", arr.shape)

# Reshape the array to a 1D array
arr_reshaped = arr.reshape((-1,))

print("Reshaped array:")
print(arr_reshaped)

Shape: (2, 3)
Reshaped array:
[1 2 3 4 5 6]




In this example, we first create a 2D NumPy array `arr` with two rows and three columns. Then, we print the shape of the array, which is `(2, 3)`. After that, we reshape the array to a 1D array using `reshape((-1,))`, and print the reshaped array.

The `-1` in the `reshape` method is a placeholder that means "calculate the correct dimension size automatically". In this case, it calculates that we need 6 elements in the 1D array to preserve the total size of the original array.

# 12. What is the best way to use shape in 3D or Nd Array?

The shape of a 3D or ND array in NumPy is a tuple that indicates the size of each dimension. You can get the shape of an array using the `shape` attribute, and you can reshape an array without changing its data using the `reshape` method.

Here's an example with a 3D array:



In [7]:
import numpy as np

# Create a 3D array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

# Print the shape of the array
print("Shape:", arr.shape)

# Reshape the array to a 2D array
arr_reshaped = arr.reshape((-1, arr.shape[-1]))

print("Reshaped array:")
print(arr_reshaped)

Shape: (2, 2, 3)
Reshaped array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]




In this example, we first create a 3D NumPy array `arr`. Then, we print the shape of the array, which is `(2, 2, 3)`. After that, we reshape the array to a 2D array with `arr.shape[-1]` (which is 3) columns, and as many rows as needed to preserve the total size of the original array. We use `-1` in the `reshape` method as a placeholder that means "calculate the correct dimension size automatically". Finally, we print the reshaped array.